apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nginx-deployment
spec:
  params:
    - name: hello-greeting
      default: Hello from a Pipeline
  tasks:
    - name: nginx
      taskRef:
        name: nginx
      params:
        - name: greeting
          value: "$(params.hello-greeting)"
    - name: alpine
      runAfter:
        - nginx
      taskRef:
        name: alpine
